services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - recipehub_net

  api:
    build: ./backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - recipehub_net

networks:
  recipehub_net:
    driver: bridge

volumes:
  mongo_data: